title: BORI'S BLOG
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  github: 250b
  instagram: 250b_

google_analytics: "G-W2REE5LBMS"

disqus:
    shortname: brianmaierjr
